### Student create
POST localhost:8080/student/create
Content-Type: application/json

{
  "name": "5",
  "surname": "3",
  "level": "3-kurs",
  "age": 20,
  "gender": "MALE",
  "createddate": "2023-03-14"

}

### Student list
GET localhost:8080/student/list

### Student getbyid
GET localhost:8080/student/get/1

### Student update
PUT localhost:8080/student/update/3
Content-Type: application/json

{
  "name":"Qo'y",
  "surname":"Alishjon",
  "age":"20"

}

### Student delete
DELETE localhost:8080/student/delete/3

### Student findname
GET localhost:8080/student/name/Eshmat

### Student findsurname
GET localhost:8080/student/surname/Eshmatov

### Student findlevel
GET localhost:8080/student/level/1-kurs

### Student findate
GET localhost:8080/student/age/18

### Student finddatebetween
GET localhost:8080/student/betweendate/2023-04-04/2023-04-05